### ISSUE TITLE
[QUESTION] Running in Kuberneters

### ISSUE THREAD

**Issue by jseiser** [jpillora/chisel#133]
Has anyone messed around with running chisel in kubernetes?  I have a use case where pods need to securely connect to remote resources, without the use a VPN.  I am able to make this work in docker, so  i think I should be able to do something here.

My thoughts were some sort of init container, which modifies outbound traffic destined for certain IP:PORTS to get redirected to the chisel container in the same pod.

No luck so far, but was curious if anyone else had did anything remotely similar with chisel.

**Comment by jseiser** [comment]
Closing out, but want to state i stated this way more complicated than it needed to be. 

Just bringup chisel container, create a service, map ports and direct traffic using the service DNS entry.

works fine.

**Comment by mikemilano** [comment]
@jseiser any chance i can see a manifeset or get a sanity check? I can get it working in Docker, but not k8s.

Here's what I've come up with. I can get the client to connect, but the proxy is not working.

```
---
apiVersion: v1
kind: Service
metadata:
  name: chiselsrv-service
spec:
  selector:
    app: chiselsrv
  ports:
    - name: chisel
      protocol: TCP
      port: 30000
      targetPort: 83
    - name: http
      protocol: TCP
      port: 30001
      targetPort: 85
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch1
  labels:
    app: chiselsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chiselsrv
  template:
    metadata:
      labels:
        app: chiselsrv
    spec:
      containers:
        - name: chiselsrv
          image: jpillora/chisel:latest
          ports:
            - containerPort: 83
              name: listen
            - containerPort: 85
              name: serve
          args:
            - server
            - "--port"
            - "83"
            - "-reverse"
```

```
chiselsrv-service   NodePort   10.32.0.196   <none>        30000:30247/TCP,30001:30345/TCP   3s
```

```
$ chisel client -v http://tunnel.example.com:30247 R:30345:localhost:8000
2020/04/13 21:42:15 client: Connecting to ws://104.154.116.30:30247
2020/04/13 21:42:15 client: Handshaking...
2020/04/13 21:42:15 client: Fingerprint 1d:c9:0c:8e:ad:21:1c:18:98:4b:42:e3:19:58:bc:b3
2020/04/13 21:42:15 client: Sending config
2020/04/13 21:42:15 client: Connected (Latency 55.973289ms)
```

Then I get not response here: http://tunnel.example.com:30345/ (obviously substituting example.com with my domain) My local system works when I proxy without k8s, so it's something with the server setup.
