### ISSUE TITLE
Support multiple path(or link), aggregate them to one virtual tunnel

### ISSUE THREAD

**Issue by CecilioGovain** [jpillora/chisel#248]
A server or client machine may have multiple IP addresses, that means, you can reach your server via multiple paths(or links), if you can aggregate these links to one virtual path, you will speed up you tunnel.

The following alternatives are not easy to use, they are written in C, you need root to run it, and can't work in Windows:
Linux Kernel implementation of [MultiPath TCP (MPTCP)](https://multipath-tcp.org/)
[Glorytun](https://github.com/angt/glorytun) is a small, simple and secure multipath UDP tunnel.
[MLVPN](https://github.com/zehome/MLVPN) - Multi-Link Virtual Public Network

To implement this feature, chisel should use config file to config the paths, the client side config may look like:
```toml
[vpaths.ssh]
protocol = "tcp"
bind = "127.0.0.1:2222"
forwardto = "127.0.0.1:22"
failover=true
balance = "weight"          #  (optional [weight]) "weight" | "leastconn" | "roundrobin" | "leastbandwidth"
[vpaths.ssh.path0]
server="https://1.2.3.4:443/path"  # chisel server side entry
if="eth0"  # on client machine , chisel use eth0 to connect to https://1.2.3.4:443/path
weight=6
[vpaths.ssh.path1]
server="https://4.3.2.1:443/path"  # chisel server side entry
if="ppp0"  # on client machine , chisel use ppp0 to connect to https://4.3.2.1:443/path
weight=4
```
If chisel support multi-path, and made it easy to deploy, this would be an awesome feature.
